name: Deploy FastAPI to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy source code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # 경로 정리
            rm -rf ~/fastapi-app
            git clone https://github.com/capstone-backtest/backtest_be_fast.git ~/fastapi-app
            cd ~/fastapi-app

            # Docker 빌드 및 재시작
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker build -t fastapi-app .
            docker run -d -p 8000:8000 --name fastapi-container fastapi-app
          EOF